services:
  postgres:
    image: postgres:17-alpine
    container_name: lari-finance-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-lari_finance}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
